######################################################################
# Automatically generated by qmake (2.01a) Thu May 3 14:41:18 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . base64
INCLUDEPATH += . base64

# Input
HEADERS += MyUi.h base64/base64.h
FORMS += duomi.ui
SOURCES += duomi.cpp MyUi.cpp base64/base64.cpp
QT += network
RC_FILE = duomi.rc
