######################################################################
# Automatically generated by qmake (2.01a) Thu May 3 14:41:18 2012
######################################################################

TEMPLATE = app
TARGET =

# Input
HEADERS += MyUi.h
FORMS += duomi.ui
SOURCES += duomi.cpp MyUi.cpp
QT += network
RC_FILE = duomi.rc
